package org.lareferencia.backend.rest;

public enum NetworkAction {
	
	START_HARVESTING,
	START_HARVESTING_BYSET,
	STOP_HARVESTING,
	ADD_VUFIND_INDEX,
	ADD_XOAI_INDEX,
	DELETE_VUFIND_INDEX,
	DELETE_XOAI_INDEX,
	CLEAN_NETWORK,
	DELETE_NETWORK

	
}
